# Generated by Django 4.2 on 2025-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("context", models.TextField()),
            ],
            options={
                "verbose_name": "Новости",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
