# Generated by Django 4.2 on 2025-05-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Savollar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("savol", models.CharField(max_length=110)),
                ("javob", models.TextField()),
            ],
            options={
                "verbose_name": "Tez-tez beriladigan savollar",
                "verbose_name_plural": "Tez-tez beriladigan savollar",
            },
        ),
    ]
