# Generated by Django 5.2.1 on 2025-05-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_savollar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "verbose_name": "Yangiliklar",
                "verbose_name_plural": "Yangiliklar",
            },
        ),
    ]
