# Generated by Django 5.2.1 on 2025-05-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_post_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurWorks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rasm", models.ImageField(upload_to="media/")),
            ],
            options={
                "verbose_name": "So'ngi ishlarimiz",
                "verbose_name_plural": "So'ngi ishlarimiz",
            },
        ),
    ]
