# Generated by Django 5.2.1 on 2025-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_ourworks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ourworks",
            name="rasm",
        ),
        migrations.AddField(
            model_name="ourworks",
            name="image",
            field=models.ImageField(default=1, upload_to="our_works/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ourworks",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
