# Generated by Django 5.2.1 on 2025-05-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ourworks_rasm_ourworks_image_ourworks_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourworks',
            options={'verbose_name': 'Наши работы', 'verbose_name_plural': 'Наши работы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='savollar',
            options={'verbose_name': 'Часто задаваемые вопросы', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterField(
            model_name='ourworks',
            name='image',
            field=models.ImageField(upload_to='our_works/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ourworks',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='savollar',
            name='javob',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='savollar',
            name='savol',
            field=models.CharField(max_length=110, verbose_name='Вопрос'),
        ),
    ]
